# 核心配置文件
core:
  # 仿真配置
  simulation:
    vehicles:
      - id: 1  # 飞行器ID
        components:
          # 按期望的逻辑顺序或任意顺序列出组件
          # StateManager会自动处理依赖关系和执行顺序
          - SimpleAtmosphere
          - RigidBodyDynamics6DoF
          - SimpleAerodynamics
          - IdealIMUSensor
          - PerfectNavigation
          - GuidanceLogic
          - ControlLogic

      # 可以轻松扩展到多飞行器
      # - id: 2
      #   components:
      #     - ...
