# 工具配置
utility:
  logger:
    console_enabled: true
    file_enabled: true
    file_path: "logs/gnc.log"
    level: "trace"
  data_logger:
    format: "hdf5"                    # "hdf5" or "csv"
    file_path: "logs/simulation_data.h5"  # Output file path
    log_frequency_hz: 100             # Logging frequency in Hz (0 = every step)
    log_metadata: true                # Include git hash, config snapshot
    selectors:                        # State selection rules
      - state: "vehicle0.TimingManager.timing_current_s"  # Cross-vehicle specific state (vehicle 0)
      - state: "vehicle1.Dynamics.position_truth_x"       # Cross-vehicle specific state (vehicle 1)
      - state: "TimingManager.timing_current_s"          # Local vehicle specific state
      - component_regex: ".*Guidance.*"            # Component pattern
        state_regex: ".*"                         # All states in component
      - component_regex: "^RigidBodyDynamics6DoF$"
        state_regex: ".*_truth_.*"
        exclude_state_regex: ".*_factor$"         # Exclusion pattern
  disturbance:
    mode: "single"  # single 或 csv
    csv_file: "config/param_sets.csv"  # CSV模式时的文件路径
    active_set: 0  # CSV模式时的当前参数集索引
    parameters:
      imu_gyro_bias: [0.01, 0.01, 0.01]
      imu_accel_bias: [0.1, 0.1, 0.1]
      imu_gyro_noise_std: 0.001
      imu_accel_noise_std: 0.01
      gps_position_bias: [2.0, 2.0, 1.0]
      gps_velocity_bias: [0.1, 0.1, 0.05]
      gps_position_noise_std: 1.0
      gps_velocity_noise_std: 0.1
      drag_factor: 1.1
      lift_factor: 1.0
      control_gain_factor: 1.0
      actuator_bias: [0.0, 0.0, 0.0]
      wind_factor: 1.0
      mass_factor: 1.0
      thrust_factor: 1.0
